_wandb:
    value:
        cli_version: 0.26.0
        e:
            0x1i0n5mu5yem8bue70voezlxacwgv4i:
                codePath: scripts/training_mnist.py
                codePathLocal: training_mnist.py
                email: patrick.mederitsch.pm@gmail.com
                executable: /home/massive_rabbit/miniforge3/envs/NeuTrObs/bin/python
                git:
                    commit: e0d04ab9cb1a5ad387b211f17fd89871d827088b
                    remote: git@github.com:Massive-Rabbit-8223/Neural-Training-Observatory.git
                host: aeon-desktop
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.39
                program: /home/massive_rabbit/Documents/GitHub/Neural-Training-Observatory/scripts/training_mnist.py
                python: CPython 3.11.15
                root: /home/massive_rabbit/Documents/GitHub/Neural-Training-Observatory/scripts
                startedAt: "2026-04-21T09:57:23.288663Z"
                writerId: 0x1i0n5mu5yem8bue70voezlxacwgv4i
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.15
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 5
lr:
    value: 0.001
model:
    value: MLP
